version: '3.8'

services:
  app:
    build: .
    container_name: cicd-dashboard
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network: